import StyledComponentsRegistry from '@/components/layout/StyledComponentsRegistry'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AntdRegistry } from '@ant-design/nextjs-registry'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'nextjs-boilerplate',
  description: 'Generated by nextjs boilerplate',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <AntdRegistry>
            {children}
          </AntdRegistry>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
